client_id = ""
name = "Zoro Low Stock Counter"
application_url = "https://shopify.dev"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/api/auth" ]
